apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agents.universe.ai
spec:
  group: universe.ai
  scope: Namespaced
  names:
    plural: agents
    singular: agent
    kind: Agent
    shortNames:
      - ag
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                role:
                  type: string
                  enum: ["worker", "manager", "director"]
                  default: "worker"
                  description: Agent role in organizational hierarchy
                team:
                  type: string
                  description: Team this agent belongs to
                manages:
                  type: array
                  items:
                    type: string
                  description: List of agent names this agent manages (for managers/directors)
                permissions:
                  type: object
                  properties:
                    canAssignTasks:
                      type: boolean
                      default: false
                    canAccessAuditLogs:
                      type: boolean
                      default: false
                    canManageTeam:
                      type: boolean
                      default: false
                  description: Role-based permissions
                image:
                  type: object
                  properties:
                    repository:
                      type: string
                    tag:
                      type: string
                    verify:
                      type: boolean
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
