apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tasks.universe.ai
spec:
  group: universe.ai
  scope: Namespaced
  names:
    plural: tasks
    singular: task
    kind: Task
    shortNames:
      - tsk
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - title
                - description
              properties:
                title:
                  type: string
                  description: Short task title
                description:
                  type: string
                  description: Detailed task description
                assignee:
                  type: string
                  description: Agent name to assign task to (optional, can be auto-assigned)
                priority:
                  type: string
                  enum: ["low", "normal", "high", "critical"]
                  default: "normal"
                  description: Task priority level
                deadline:
                  type: string
                  format: date-time
                  description: Task deadline in ISO 8601 format
                requiredTools:
                  type: array
                  items:
                    type: string
                  description: List of tools the agent must have access to
                zone:
                  type: string
                  description: Zone/department the task belongs to
                dependencies:
                  type: array
                  items:
                    type: string
                  description: List of task names that must complete before this task
                input:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  description: Input data for the task
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum: ["Pending", "Assigned", "InProgress", "Completed", "Failed", "Cancelled"]
                  description: Current task phase
                assignedAgent:
                  type: string
                  description: Agent currently assigned to this task
                startTime:
                  type: string
                  format: date-time
                  description: When task execution started
                completionTime:
                  type: string
                  format: date-time
                  description: When task completed or failed
                attempts:
                  type: integer
                  description: Number of execution attempts
                result:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  description: Task execution result
                error:
                  type: string
                  description: Error message if task failed
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
      additionalPrinterColumns:
        - name: Status
          type: string
          jsonPath: .status.phase
        - name: Agent
          type: string
          jsonPath: .status.assignedAgent
        - name: Priority
          type: string
          jsonPath: .spec.priority
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
