apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agents.universe.ai
spec:
  group: universe.ai
  scope: Namespaced
  names:
    plural: agents
    singular: agent
    kind: Agent
    shortNames: ["ag"]
  subresources:
    status: {}
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: object
                  properties:
                    repository:
                      type: string
                    tag:
                      type: string
                    verify:
                      type: boolean
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
