apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: universes.universe.ai
spec:
  group: universe.ai
  scope: Namespaced
  names:
    plural: universes
    singular: universe
    kind: Universe
    shortNames: ["uni"]
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
